schemaVersion: 2.2.0
metadata:
  name: testcontainers-sample
components:
  - name: tooling-container
    container:
      env:
        - name: DOCKER_HOST
          value: 'tcp://127.0.0.1:2475'
        - name: CONTAINER_HOST
          value: 'tcp://127.0.0.1:2475'
        - name: TESTCONTAINERS_RYUK_DISABLED
          value: 'true'
        - name: TESTCONTAINERS_CHECKS_DISABLE
          value: 'true'
      image: quay.io/mloriedo/universal-developer-image:kubedock
      memoryRequest: 2Gi
      memoryLimit: 11Gi
      cpuRequest: 1000m
      cpuLimit: 4000m
      endpoints:
        - exposure: none
          name: kubedock
          protocol: tcp
          targetPort: 2475      
commands:
  - id: start-kubedock
    exec:
      label: '1. Start kubedock'
      component: tooling-container
      commandLine: kubedock server --port-forward
  - id: test
    exec:
      label: '2. Test'
      component: tooling-container
      commandLine: ./gradlew test
  - id: run
    exec:
      label: '3. Run'
      component: tooling-container
      commandLine: ./gradlew run
  - id: docker-run
    exec:
      label: '4. docker run sample'
      component: tooling-container
      commandLine: docker run --name httpd -d -p 8080:8080 python python -m http.server 8080
  - id: podman-run
    exec:
      label: '5. podman run sample'
      component: tooling-container
      commandLine: podman --remote --url "tcp://127.0.0.1:2475" run --name httpd -d -p 8080:8080 python python -m http.server 8080
