schemaVersion: 2.2.0
metadata:
  name: testcontainers-sample
parent:
  uri: https://raw.githubusercontent.com/l0rd/micronaut-sample/devfile-and-poststart/extra-tools/parent-devfile.yaml
  components:
    - name: tooling-container
      container: 
        env:
          - name: EXTRA_TOOLS_KUBEDOCK
            value: 'true'
          - name: EXTRA_TOOLS_JAVA_VERSION
            value: '17.0.3-tem'
commands:
  - id: test
    exec:
      label: '1. Test'
      component: tooling-container
      commandLine: ./gradlew test
  - id: run
    exec:
      label: '2. Run'
      component: tooling-container
      commandLine: ./gradlew run
  - id: podman-run
    exec:
      label: '3. podman run sample'
      component: tooling-container
      commandLine: podman --remote --url "tcp://127.0.0.1:2475" run --name httpd -d -p 8080:8080 python python -m http.server 8080
