schemaVersion: 2.2.0
metadata:
  name: big
components:
  - name: tooling-container
    container:
      image: quay.io/mloriedo/universal-developer-image:kubedock
      memoryRequest: 2Gi
      memoryLimit: 16Gi
      cpuRequest: 1000m
      cpuLimit: 4000m
commands:
  - id: run
    exec:
      component: tooling-container
      commandLine: ./gradlew run
  - id: start-kubedock
    exec:
      component: tooling-container
      commandLine: kubedock server --port-forward --inspector   
  - id: docker-run
    exec:
      component: tooling-container
      commandLine: docker run --name httpd -d -p 8080 docker.io/library/python python -m http.server 8080 && echo "test connection using localhost $(docker port httpd 8080)"
