schemaVersion: 2.2.0
metadata:
  name: testcontainers-sample
components:
  - name: tooling-container
    container:
      image: quay.io/mloriedo/universal-developer-image:kubedock
      memoryRequest: 2Gi
      memoryLimit: 8Gi
      cpuRequest: 1000m
      cpuLimit: 4000m
      endpoints:
        - exposure: none
          name: kubedock
          protocol: tcp
          targetPort: 2475      
commands:
  - id: test
    exec:
      label: '1. Test'
      component: tooling-container
      commandLine: ./gradlew test
  - id: run
    exec:
      label: '2. Run'
      component: tooling-container
      commandLine: ./gradlew run
  - id: podman-run
    exec:
      label: '3. podman run sample'
      component: tooling-container
      commandLine: podman --remote --url "tcp://127.0.0.1:2475" run --name httpd -d -p 8080:8080 python python -m http.server 8080
